### ISSUE TITLE
Please give a proper way to run this repository

### ISSUE THREAD

**Issue by dubesar** [JaZz-9/Try-First#1]
How can we run this repo as I am getting lots of errors? Please give a demo of how its to be done.

**Comment by dubesar** [comment]
Can somebody tell where the models has to be kept?

**Comment by JaZz-9** [comment]
For the flask part, put all the HTML files in the 'template' folder and all other assets in the 'static' folder.  And rest of models' python script is to be kept in the same folder as static and template.

**Comment by dubesar** [comment]
@JaZz-9 can you connect to me if possible, I need to get this done asap. Also, have to improve this model
